name: test

on:
  - pull_request
  - push

jobs:
  testing:
    strategy:
      matrix:
        brew_version: ["3.6.21", "4.0.15", "latest"]
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew:${{ matrix.brew_version }}
      options: --user root
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_FROM_API: 1
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: install git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          brew install node
          node --version

      - name: test install
        run: |
          brew tap appleboy/tap "${PWD}"
          brew install appleboy/tap/drone-git-push
          drone-git-push --version
