name: test

on:
  - pull_request
  - push

jobs:
  testing:
    strategy:
      matrix:
        brew_version: ["3.6.21", "4.0.15", "latest"]
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew:${{ matrix.brew_version }}
      options: --user root
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_FROM_API: 1
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: test install
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git config --global --add safe.directory /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core
          brew tap appleboy/tap "${PWD}"
          brew install appleboy/tap/gorush
          gorush --version
          brew install appleboy/tap/codegpt
          codegpt version
          brew install appleboy/tap/drone-git-push
          drone-git-push --version
          brew install appleboy/tap/drone-lambda
          drone-lambda --version
          brew install appleboy/tap/drone-scp
          drone-scp --version
          brew install appleboy/tap/drone-ssh
          drone-ssh --version
