name: test

on:
  - pull_request
  - push

jobs:
  testing:
    strategy:
      matrix:
        brew_version: ["3.6.14", "latest"]
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew:${{ matrix.brew_version }}
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: actions/checkout@v3
      - name: test install
        run: |
          brew tap appleboy/tap "${PWD}"
          brew install appleboy/tap/drone-git-push
          drone-git-push --version
